spring.application.name=FileWatcherService

# ===============================
# SERVER CONFIG
# ===============================
server.port=


# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=<ADD DATABASE URL HERE>
spring.datasource.username=<ADD DATABASE USERNAME HERE>
spring.datasource.password=<ADD DATABASE PASSWORD HERE>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# ===============================
# BATCH INSERT OPTIMIZATION
# (Important for large CSV)
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=false


# ===============================
# FILE WATCHER CONFIG
# ===============================
file.import.path= <ADD PATH HERE>


# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=INFO
